/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RedParagraph {
    }
}
declare global {
    interface HTMLRedParagraphElement extends Components.RedParagraph, HTMLStencilElement {
    }
    var HTMLRedParagraphElement: {
        prototype: HTMLRedParagraphElement;
        new (): HTMLRedParagraphElement;
    };
    interface HTMLElementTagNameMap {
        "red-paragraph": HTMLRedParagraphElement;
    }
}
declare namespace LocalJSX {
    interface RedParagraph {
    }
    interface IntrinsicElements {
        "red-paragraph": RedParagraph;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "red-paragraph": LocalJSX.RedParagraph & JSXBase.HTMLAttributes<HTMLRedParagraphElement>;
        }
    }
}
