/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface RedParagraph {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRedParagraphElement extends Components.RedParagraph, HTMLStencilElement {
    }
    var HTMLRedParagraphElement: {
        prototype: HTMLRedParagraphElement;
        new (): HTMLRedParagraphElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "red-paragraph": HTMLRedParagraphElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface RedParagraph {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "red-paragraph": RedParagraph;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "red-paragraph": LocalJSX.RedParagraph & JSXBase.HTMLAttributes<HTMLRedParagraphElement>;
        }
    }
}
